apiVersion: v1
kind: Secret
metadata:
  name: hill-hill-backend-secrets
type: Opaque
stringData:
  # CHANGE THIS IN PRODUCTION!
  # Generate a secure key with: python3 -c "import secrets; print(secrets.token_hex(32))"
  jwt-secret-key: "CHANGE-THIS-IN-PRODUCTION-USE-A-SECURE-RANDOM-KEY"


